/**
 * Find symmetries on the main process.
 *
 * @packageDocumentation
 */
import {ipcMain} from "electron";
import tmp from "tmp";
import fs from "fs-extra";
import path from "node:path";
import type {FindSymmetriesParams} from "../types";
import {basisToLengthAngles} from "./ReaderHelpers";
import {getAtomicSymbol} from "./AtomData";

const removeWorkingDir = (wd: tmp.DirResult, workingDir: string): void => {

	let workFile = path.join(workingDir, "FOR007.DAT");
	fs.removeSync(workFile);
	workFile = path.join(workingDir, "RGS.OUT");
	fs.removeSync(workFile);
	workFile = path.join(workingDir, "INPUT.DAT");
	fs.removeSync(workFile);
	workFile = path.join(workingDir, "OUTPUT.DAT");
	fs.removeSync(workFile);

	wd.removeCallback();
};


/**
 * Setup channel to find symmetries from main window
 */
export const setupChannelFindSymmetries = (): void => {

	ipcMain.handle("FIND:SYMMETRIES", (_event, payload: string) => {

		const params = JSON.parse(payload) as FindSymmetriesParams;

		// Create a temporary working directory
		const tmpobj = tmp.dirSync({unsafeCleanup: true});
		const workingDir = tmpobj.name;
		const inputFile = path.join(workingDir, "INPUT.DAT");
		const fp = fs.openSync(inputFile, "w");

		// Write the script
		fs.writeSync(fp, "NDLG;NOKD\n");
		fs.writeSync(fp, "T 'Generated by STMng'\n");

		// Returns lena, lenb, lenc, alpha, beta, gamma
		const la = basisToLengthAngles(params.basis);
		fs.writeSync(fp, `Z ${la[0]} ${la[1]} ${la[2]} ${la[3]} ${la[4]} ${la[5]}\n`);

		// Space group
		const sg = params.spaceGroup.replace(" ", "");
		if(params.ignoreSymmetries || sg === "") fs.writeSync(fp, "HMS 'P1'\n");
		else fs.writeSync(fp, `HMS '${sg}'\n`);

		// Required dummy atoms
		fs.writeSync(fp, "ATOM Fake    1  0.500000  0.500000  0.500000\n");
		fs.writeSync(fp, "ATOM Fake    2  0.000000  0.000000  0.000000\n");

		// The input atoms
		const natoms = params.atomsZ.length;
		for(let i=0; i < natoms; ++i) {

			const atomSymbol = getAtomicSymbol(params.atomsZ[i]).padEnd(4, " ");
			const idx = (i+3).toString().padStart(4, " ");
			const fcX = params.fractionalCoordinates[i*3+0].toFixed(6).padEnd(9, " ");
			const fcY = params.fractionalCoordinates[i*3+1].toFixed(6).padEnd(9, " ");
			const fcZ = params.fractionalCoordinates[i*3+2].toFixed(6).padEnd(9, " ");
			fs.writeSync(fp, `ATOM ${atomSymbol} ${idx} ${fcX} ${fcY} ${fcZ}\n`);
		}

		// The computation request
		fs.writeSync(fp, `SSI ${params.tolS} ${params.tolT} ${params.tolG};;\n`);
		fs.writeSync(fp, "RGS;\n");
		fs.writeSync(fp, "GET RGS.OUT;\n");
		fs.writeSync(fp, "PUTC OUTPUT.DAT;\n");
		fs.writeSync(fp, "CLSE;\n");
		fs.closeSync(fp);

		// Invoke the KPLOT executable

		// TBD

		// Close the working space
		removeWorkingDir(tmpobj, workingDir);
		return "";
	});
};
