/**
 * Find symmetries on the main process.
 *
 * @packageDocumentation
 */
import {ipcMain, app} from "electron";
import tmp from "tmp";
import log from "electron-log";
import fs from "fs-extra";
import * as rd from "node:readline/promises";
import path from "node:path";
import {execSync} from "node:child_process";
import {fileURLToPath} from "node:url";
import {extractBasis, fractionalToCartesianCoordinates,
		basisToLengthAngles, getStructureAppearance} from "./ReaderWriterHelpers";
import {getAtomicSymbol, getAtomicNumber} from "../modules/AtomData";
import type {FindSymmetriesParams} from "../types";
import type {Structure, Atom} from "../../types";

/**
 * Remove the temporary directory used by KPLOT
 *
 * @param wd - Temporary directory data
 * @param workingDir - Path of the working directory
 */
const removeWorkingDir = (wd: tmp.DirResult, workingDir: string): void => {

	let workFile = path.join(workingDir, "FOR007.DAT");
	fs.removeSync(workFile);
	workFile = path.join(workingDir, "RGS.OUT");
	fs.removeSync(workFile);
	workFile = path.join(workingDir, "OUTPUT.DAT");
	fs.removeSync(workFile);

	wd.removeCallback();
};

/**
 * Setup channel to find symmetries from main window
 */
export const setupChannelFindSymmetries = (): void => {

	ipcMain.handle("FIND:SYMMETRIES", async (_event, payload: string) => {

		const params = JSON.parse(payload) as FindSymmetriesParams;

		// If space group contains symmetry cards instead of symbol, ignore it
		if(!params.ignoreSymmetries && /[(\nxyz]/i.test(params.spaceGroup)) {
			params.ignoreSymmetries = true;
		}

		// Create a temporary working directory
		const tmpobj = tmp.dirSync({unsafeCleanup: true, prefix: "stm-ng"});
		const workingDir = tmpobj.name;

		// Write the script into a variable
		let stdin = "NDLG;NOKD\nT 'Generated by STMng'\n";

		// Compute lena, lenb, lenc, alpha, beta, gamma
		// Put them in the script
		const la = basisToLengthAngles(params.basis);
		stdin += `Z ${la[0]} ${la[1]} ${la[2]} ${la[3]} ${la[4]} ${la[5]}\n`;

		// Space group
		const sg = params.spaceGroup.replaceAll(" ", "");
		stdin += params.ignoreSymmetries || sg === "" ? "HMS 'P1'\n" : `HMS '${sg}'\n`;

		// Required dummy atoms
		stdin += "ATOM Fake    1 0.500000  0.500000  0.500000\n";
		stdin += "ATOM Fake    2 0.000000  0.000000  0.000000\n";

		// The input atoms
		const natoms = params.atomsZ.length;
		for(let i=0; i < natoms; ++i) {

			const atomSymbol = getAtomicSymbol(params.atomsZ[i]).padEnd(4, " ");
			const idx = (i+3).toString().padStart(4, " ");
			const fcX = params.fractionalCoordinates[i*3].toFixed(6).padEnd(9, " ");
			const fcY = params.fractionalCoordinates[i*3+1].toFixed(6).padEnd(9, " ");
			const fcZ = params.fractionalCoordinates[i*3+2].toFixed(6).padEnd(9, " ");
			stdin += `ATOM ${atomSymbol} ${idx} ${fcX} ${fcY} ${fcZ}\n`;
		}

		// Finish the computation request
		stdin += `SSI ${params.tolS} ${params.tolT} ${params.tolG}\n`;
		stdin += "RGS\nGET RGS.OUT\nPUTC OUTPUT.DAT\nCLSE\n";

		// Find the KPLOT executable
		const mainSourceDirectory = path.dirname(fileURLToPath(import.meta.url));
		const kplot = app.isPackaged ?
								path.resolve(process.resourcesPath, "app.asar.unpacked/dist/bin/kplot.mingw.exe") :
								path.join(mainSourceDirectory, "..", "public", "bin", "kplot.mingw.exe");

		// Execute KPLOT
		const stdout = execSync(`"${kplot}"`, {windowsHide: true, cwd: workingDir, input: stdin});
		log.info(stdout.toString("utf8"));

		// The structure to be filled by the recomputed one
		const out: Structure = {
			crystal: {
				basis: [0, 0, 0, 0, 0, 0, 0, 0, 0],
				origin: [0, 0, 0],
				spaceGroup: ""
			},
			atoms: [],
			bonds: [],
			look: {},
			volume: []
		};

		// Read Kplot output
		let lines;
		try {
			const outputFile = path.join(workingDir, "OUTPUT.DAT");
			if(!fs.existsSync(outputFile)) throw Error("Find symmetries computation failed");
			const stream = fs.createReadStream(outputFile);
			lines = rd.createInterface(stream);
		}
		catch(error: unknown) {
			log.error((error as Error).message);
			removeWorkingDir(tmpobj, workingDir);
			return {payload: "Error", error: (error as Error).message};
		}
		for await (const line of lines) {

			if(line.startsWith("Z ")) {
				// Z   11.50200  11.50200  11.50200   90.0000   90.0000   90.0000
				const fields = line.trim().split(/ +/);

				const a = Number.parseFloat(fields[1]);
				const b = Number.parseFloat(fields[2]);
				const c = Number.parseFloat(fields[3]);
				const alpha = Number.parseFloat(fields[4]);
				const beta  = Number.parseFloat(fields[5]);
				const gamma = Number.parseFloat(fields[6]);

				out.crystal.basis = extractBasis(a, b, c, alpha, beta, gamma);
			}
			else if(line.startsWith("HMS ")) {
				// HMS 'IA-3D   ' (  230)
				out.crystal.spaceGroup = line.replace(/^HMS +'([^']+)'.*$/, "$1").trim();
			}
			else if(line.startsWith("ATOM ")) {
				// ATOM (   1) 'Fake'     '1   '       .500000   .500000   .500000     .3000    0
				// ATOM (   2) 'Fake'     '2   '       .000000   .000000   .000000     .3000    0
				// ATOM (   3) 'Mg  '     '0   '       .750000   .375000   .000000     .3000    0
				// ATOM (   4) 'Al  '     '1   '       .000000   .500000   .000000     .3000    0
				// ATOM (   5) 'Si  '     '2   '       .750000   .125000   .000000     .3000    0
				// ATOM (   6) 'O   '     '3   '       .847199   .533300   .049800     .3000    0

				const element = line.slice(13, 17).trim();
				if(element === "Fake") continue;

				// Fractional coordinates converted to cartesian coordinates
				const fields = line.slice(32).trim().split(/ +/);
				const fx = Number.parseFloat(fields[0]);
				const fy = Number.parseFloat(fields[1]);
				const fz = Number.parseFloat(fields[2]);

				const atom: Atom = {
					label: element,
					atomZ: getAtomicNumber(element),
					position: fractionalToCartesianCoordinates(out.crystal.basis, fx, fy, fz)
				};
				out.atoms.push(atom);
			}
		}
		out.look = getStructureAppearance(out.atoms);
		out.bonds = [];

		// Remove the working directory and return the computed structure
		removeWorkingDir(tmpobj, workingDir);
		return {payload: JSON.stringify(out)};
	});
};
