/**
 * Reader for ENERGY auxiliary file generated by CP2K
 * The files are "goodStructures" and "BESTIndividuals"
 *
 * @packageDocumentation
 *
 * @author Mario Valle "mvalle at ikmail.com"
 * @since 2025-12-24
 */
import {createReadStream} from "node:fs";
import {createInterface} from "node:readline/promises";
import type {Structure} from "@/types";

/**
 * Read the CP2K generated energy file
 *
 * @param filename - Filename to be read as CP2K auxiliary file
 * @param mainStructures - The already read main structure
 * @param appendFrom - If these steps should be appended to the main structure
 * @returns Main structures trajectory
 */
export const readAuxCP2K = async (filename: string,
							  	  mainStructures: Structure[],
							  	  appendFrom: number): Promise<Structure[]> => {

	let lineNumber = 1;
	let energyPerAtom = false;
	let column = 0;
	const energies: number[] = [];

	// Sanity check
	const mainLength = mainStructures?.length ?? 0;
	if(mainLength === 0) throw Error("Missing main structures");
	if(appendFrom >= mainLength) {
		throw Error(`Invalid append position ${appendFrom} on length ${mainLength}`);
	}

	const stream = createInterface(createReadStream(filename, {encoding: "utf8"}));
	for await (const line of stream) {

		if(lineNumber === 1) {

			const fields = line.toLowerCase().trim().split(/\s+/);
			const n = fields.length;
			for(let i=0; i < n; ++i) {
				if(fields[i].startsWith("enthalp")) {
					column = i;
					break;
				}
			}
			++lineNumber;
		}
		else if(lineNumber === 2) {
			energyPerAtom = line.includes("/atom");
			++lineNumber;
		}
		else {
			// eslint-disable-next-line unicorn/better-regex
			const ln = line.trim().replaceAll(/\[[\d ]+\]/g, "[]").split(/\s+/);
			energies.push(Number.parseFloat(ln[column]));
		}
	}

	const currentLength = mainLength - appendFrom;
	if(energies.length < currentLength) {
		throw Error(`Too few energies read (${energies.length} instead of ${currentLength})`);
	}

	for(let i=0; i < currentLength; ++i) {
		const structure = mainStructures[i+appendFrom];
		const energyFromFile = energies[i];
		structure.extra.energy = energyPerAtom ?
										energyFromFile :
										energyFromFile/structure.atoms.length;
	}

	return mainStructures;
};
