/**
 * Writer for POSCAR formatted files
 *
 * @packageDocumentation
 */

import fs from "node:fs";
import {cartesianToFractionalCoordinates, format} from "../modules/ReaderWriterHelpers";
import type {Structure, MainResponse} from "../../types";
import type {WriterImplementation} from "../types";

export class WriterPOSCAR implements WriterImplementation {

	writeStructure(filename: string, structures: Structure[]): MainResponse {

		try {
			const fd = fs.openSync(filename, "w");
			for(const structure of structures) {

				// Access the structure
				const {crystal, atoms} = structure;
				const {basis} = crystal;

				// If no unit cell return error
				if(basis.every((value) => value === 0)) {
					fs.closeSync(fd);
					return {payload: "Error", error: "Cannot write POSCAR if unit cell missing"};
				}

				// Comment line
				fs.writeSync(fd, "Generated by STMng\n1.000\n");

				// Unit cell
				fs.writeSync(fd,
						    `${format(basis[0])} ${format(basis[1])} ${format(basis[2])}\n`);
				fs.writeSync(fd,
							`${format(basis[3])} ${format(basis[4])} ${format(basis[5])}\n`);
				fs.writeSync(fd,
							`${format(basis[6])} ${format(basis[7])} ${format(basis[8])}\n`);

				// Atom counts
				const atomCounts = new Map<number, number>();
				for(const atom of atoms) {

					const count = atomCounts.get(atom.atomZ);
					atomCounts.set(atom.atomZ, count ? count+1 : 1);
				}

				let line = "";
				for(const item of atomCounts) {
					line += ` ${item[1]}`;
				}
				line += "\nDirect\n";
				fs.writeSync(fd, line);

				const fc = cartesianToFractionalCoordinates(structure);
				for(const item of atomCounts) {
					let idx = 0;
					for(const atom of atoms) {
						if(atom.atomZ === item[0]) {
							const x = format(fc[3*idx]);
							const y = format(fc[3*idx+1]);
							const z = format(fc[3*idx+2]);
							fs.writeSync(fd, `${x} ${y} ${z}\n`);
						}
						++idx;
					}
				}
			}
			fs.closeSync(fd);

			return {payload: "Success!"};
		}
		catch(error: unknown) {
			return {payload: "Error", error: (error as Error).message};
		}
	}
}
