/**
 * Writer for CHGCAR formatted files
 *
 * @packageDocumentation
 *
 * @author Mario Valle "mvalle at ikmail.com"
 * @since 2024-07-05
 *
 * Copyright 2026 Mario Valle
 *
 * This file is part of STMng.
 *
 * STMng is free software: you can redistribute it and/or modify
 * it under the terms of the version 3 of the GNU General Public License
 * as published by the Free Software Foundation.
 *
 * STMng is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with STMng. If not, see <http://www.gnu.org/licenses/>.
 */
import {openSync, writeSync, closeSync} from "node:fs";
import {reducingToFractionalCoordinates, format, hasNoUnitCell} from "../modules/Helpers";
import type {Structure, WriterImplementation, CtrlParams} from "@/types";

export class WriterCHGCAR implements WriterImplementation {

	writeStructure(filename: string, structures: Structure[]): CtrlParams {

		try {
			const fd = openSync(filename, "w");
			for(const structure of structures) {

				// Access the structure
				const {crystal, volume} = structure;
				const {basis} = crystal;

				// If no unit cell return error
				if(hasNoUnitCell(basis)) {
					closeSync(fd);
					return {error: "Cannot write CHGCAR if unit cell missing"};
				}

				// Comment line
				writeSync(fd, "Generated by STMng\n1.000\n");

				// Unit cell
				writeSync(fd, `${format(basis[0])} ${format(basis[1])} ${format(basis[2])}\n`);
				writeSync(fd, `${format(basis[3])} ${format(basis[4])} ${format(basis[5])}\n`);
				writeSync(fd, `${format(basis[6])} ${format(basis[7])} ${format(basis[8])}\n`);

				// Compute fractional coordinates removing duplicates
				const reduced = reducingToFractionalCoordinates(structure);

				let line = "";
				for(const item of reduced.atomSymbols) {
					line += ` ${item}`;
				}
				line += "\n";
				for(const item of reduced.atomCount) {
					line += ` ${item}`;
				}
				line += "\nDirect\n";
				writeSync(fd, line);

				for(const atom of reduced.atoms) {
					const fc = atom.frac;
					const x = format(fc[0]);
					const y = format(fc[1]);
					const z = format(fc[2]);
					writeSync(fd, `${x} ${y} ${z}\n`);
				}

				// Write values (10 values per line)
				if(volume.length === 0) continue;
				writeSync(fd, "\n");
				for(const set of volume) {
					const {values, sides} = set;
					writeSync(fd, ` ${sides[0]} ${sides[1]} ${sides[2]}`);
					const len = values.length;
					let valuesLine = "";
					for(let i=0; i < len; ++i) {
						if(i % 10 === 0) {
							writeSync(fd, `${valuesLine}\n`);
							valuesLine = "";
						}
						valuesLine += values[i].toExponential(5).padStart(12);
					}
					if(valuesLine !== "") writeSync(fd, `${valuesLine}\n`);
				}
			}
			closeSync(fd);

			return {payload: "Success!"};
		}
		catch(error) {
			return {error: (error as Error).message};
		}
	}
}
