/**
 * Writer for POSCAR formatted files
 *
 * @packageDocumentation
 *
 * @author Mario Valle "mvalle at ikmail.com"
 * @since 2024-07-05
 */

import {openSync, writeSync, closeSync} from "node:fs";
import {format, hasNoUnitCell, reducingToFractionalCoordinates} from "../modules/Helpers";
import type {Structure, WriterImplementation, CtrlParams} from "@/types";

export class WriterPOSCAR implements WriterImplementation {

	writeStructure(filename: string, structures: Structure[]): CtrlParams {

		try {
			const fd = openSync(filename, "w");
			for(const structure of structures) {

				// Access the structure
				const {crystal, atoms, extra} = structure;

				// Step label
				const step = (extra.step === undefined) ? "" : ` (step: ${extra.step})`;

				// Extra sanity check
				if(!crystal || atoms.length === 0) {
					closeSync(fd);
					return {payload: "Error",
							error: `Cannot write POSCAR if structure is malformed${step}`};
				}

				// If no unit cell return error
				const {basis} = crystal;
				if(hasNoUnitCell(basis)) {
					closeSync(fd);
					return {payload: "Error",
							error: `Cannot write POSCAR if unit cell missing${step}`};
				}

				// Comment line
				writeSync(fd, `Generated by STMng${step}\n1.000\n`);

				// Unit cell
				writeSync(fd, `${format(basis[0])} ${format(basis[1])} ${format(basis[2])}\n`);
				writeSync(fd, `${format(basis[3])} ${format(basis[4])} ${format(basis[5])}\n`);
				writeSync(fd, `${format(basis[6])} ${format(basis[7])} ${format(basis[8])}\n`);

				// Compute fractional coordinates removing duplicates
				const reduced = reducingToFractionalCoordinates(structure);

				let line = "";
				for(const item of reduced.atomSymbols) {
					line += ` ${item}`;
				}
				line += "\n";
				for(const item of reduced.atomCount) {
					line += ` ${item}`;
				}
				line += "\nDirect\n";
				writeSync(fd, line);

				for(const atom of reduced.atoms) {
					const fc = atom.frac;
					const x = format(fc[0]);
					const y = format(fc[1]);
					const z = format(fc[2]);
					writeSync(fd, `${x} ${y} ${z}\n`);
				}
			}
			closeSync(fd);

			return {payload: "Success!"};
		}
		catch(error) {
			return {payload: "Error", error: (error as Error).message};
		}
	}
}
