/**
 * Writer for CHGCAR formatted files
 *
 * @packageDocumentation
 *
 * @author Mario Valle "mvalle\@ikmail.com"
 * @since 2024-07-05
 */

import fs from "node:fs";
import {cartesianToFractionalCoordinates, format} from "../modules/Helpers";
import type {Structure, WriterImplementation, CtrlParams} from "@/types";

export class WriterCHGCAR implements WriterImplementation {

	writeStructure(filename: string, structures: Structure[]): CtrlParams {

		try {
			const fd = fs.openSync(filename, "w");
			for(const structure of structures) {

				// Access the structure
				const {crystal, atoms, volume} = structure;
				const {basis} = crystal;

				// If no unit cell return error
				if(basis.every((value: number) => value === 0)) {
					fs.closeSync(fd);
					return {error: "Cannot write CHGCAR if unit cell missing"};
				}

				// Comment line
				fs.writeSync(fd, "Generated by STMng\n1.000\n");

				// Unit cell
				fs.writeSync(fd,
						    `${format(basis[0])} ${format(basis[1])} ${format(basis[2])}\n`);
				fs.writeSync(fd,
							`${format(basis[3])} ${format(basis[4])} ${format(basis[5])}\n`);
				fs.writeSync(fd,
							`${format(basis[6])} ${format(basis[7])} ${format(basis[8])}\n`);

				// Atom counts
				const atomCounts = new Map<number, number>();
				for(const atom of atoms) {

					const count = atomCounts.get(atom.atomZ);
					atomCounts.set(atom.atomZ, count ? count+1 : 1);
				}

				let line = "";
				for(const item of atomCounts) {
					line += ` ${item[1]}`;
				}
				line += "\nDirect\n";
				fs.writeSync(fd, line);

				const fc = cartesianToFractionalCoordinates(structure);
				for(const item of atomCounts) {
					let idx = 0;
					for(const atom of atoms) {
						if(atom.atomZ === item[0]) {
							const j = 3*idx;
							const x = format(fc[j]);
							const y = format(fc[j+1]);
							const z = format(fc[j+2]);
							fs.writeSync(fd, `${x} ${y} ${z}\n`);
						}
						++idx;
					}
				}

				// Write values (10 values per line)
				if(volume.length === 0) continue;
				fs.writeSync(fd, "\n");
				for(const set of volume) {
					const {values, sides} = set;
					fs.writeSync(fd, ` ${sides[0]} ${sides[1]} ${sides[2]}`);
					const len = values.length;
					let valuesLine = "";
					for(let i=0; i < len; ++i) {
						if(i % 10 === 0) {
							fs.writeSync(fd, `${valuesLine}\n`);
							valuesLine = "";
						}
						valuesLine += values[i].toExponential(5).padStart(12);
					}
					if(valuesLine !== "") fs.writeSync(fd, `${valuesLine}\n`);
				}
			}
			fs.closeSync(fd);

			return {payload: "Success!"};
		}
		catch(error) {
			return {error: (error as Error).message};
		}
	}
}
