/** Declaration file generated by dts-gen */
// eslint-disable-next-line @typescript-eslint/no-shadow
export class Text {
    constructor();
    sync(): void;

	public text: string;
	public fontSize: number;
	public color: number;
}
