name: Deploy site
run-name: Pushing doc to STMng-pages repository
on:
  # - create

  # Allows you to run this workflow manually from the Actions tab
  - workflow_dispatch

permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between
# the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production
# deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository-name: crystalfp/STMng-pages
          target-folder: .
