name: Push webpages to another repository
run-name: ${{ github.actor }} is pushing webpages to another repository
on:
  # - create

  # Allows you to run this workflow manually from the Actions tab
  - workflow_dispatch

env:
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

# Allow only one concurrent deployment, skipping runs queued between
# the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production
# deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Copy Pages
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        with:
          source-files: 'public/doc/'
          destination-username: 'crystalfp'
          destination-repository: 'https://github.com/crystalfp/STMng-pages'
          destination-directory: '.'
          commit-email: 'mvalle@ikmail.com'
